"""Game-style Lean exam environment for step-level provers.

Mirrors the Lean game loop the way a human experiences it:

  - the exam STARTS from a certified statement (goal + assumptions given,
    never generated by the solver);
  - the solver plays one tactic at a time and sees the resulting goal
    state(s), exactly like the game's Active Goal panel;
  - a rejected tactic leaves the state unchanged (the game's Retry);
  - ``rollback`` lets the solver choose WHERE to retry from, not just
    restart;
  - ``inspect`` opens a palette card (tactic doc or theorem signature) —
    names are free, details are an explicit action.

One verifier call per step, no sorry games: verifying the tactic prefix
without a closing body either (a) errors on the new tactic → rejected,
(b) errors with ``unsolved goals`` whose body IS the pretty goal state →
step accepted, or (c) completes → exam passed.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Awaitable, Callable, Dict, List, Optional

from src.certification.alignment import strip_proof_body
from src.evaluation.lean_verifier import LeanVerifyResult, verify_lean_proof

Verifier = Callable[..., Awaitable[LeanVerifyResult]]

_UNSOLVED_RE = re.compile(r"unsolved goals", re.IGNORECASE)
_NO_GOALS_RE = re.compile(r"no goals", re.IGNORECASE)


@dataclass
class ExamObservation:
    goals: List[str]
    status: str  # "active" | "accepted" | "rejected" | "solved" | "error"
    message: str = ""
    card: Optional[Dict[str, str]] = None
    steps: List[str] = field(default_factory=list)
    step_count: int = 0
    done: bool = False
    success: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "goals": self.goals,
            "status": self.status,
            "message": self.message,
            "card": self.card,
            "steps": list(self.steps),
            "step_count": self.step_count,
            "done": self.done,
            "success": self.success,
        }


_LAKE_NOISE_RE = re.compile(r"^(warning|info|error): (manifest out of date|no manifest)", re.IGNORECASE)


def _is_lake_noise(block: str) -> bool:
    """A block made only of lake's own messages (``warning: manifest out of
    date: ...``) is not a goal. lake writes them to stderr ahead of Lean's
    diagnostics, and a checkout whose package metadata disagrees with the
    manifest by so much as a branch name emits them on every call; folded into
    the goal state, a prover would be shown a lake warning as an open goal."""
    lines = [line.strip() for line in block.splitlines() if line.strip()]
    return bool(lines) and all(_LAKE_NOISE_RE.match(line) for line in lines)


def _split_goal_blocks(body: str) -> List[str]:
    """Split an ``unsolved goals`` body into individual goal displays."""
    text = re.sub(r"^\s*unsolved goals\s*", "", body, flags=re.IGNORECASE).strip()
    if not text:
        return []
    blocks = [block.strip() for block in re.split(r"\n\s*\n", text) if block.strip()]
    blocks = [block for block in blocks if not _is_lake_noise(block)]
    return blocks or ([text] if not _is_lake_noise(text) else [])


class LeanExamEnv:
    """One exam = one certified statement + a palette + a verifier."""

    def __init__(
        self,
        *,
        formal_statement: str,
        lean_header: str,
        palette: Optional[Dict[str, Dict[str, str]]] = None,
        verifier: Optional[Verifier] = None,
        max_steps: int = 40,
        lean_timeout: float = 300.0,
        strict_steps: bool = False,
    ) -> None:
        self.statement = strip_proof_body(formal_statement)
        header = (lean_header or "import Mathlib").rstrip()
        if "set_option autoImplicit false" not in header:
            header = f"{header}\nset_option autoImplicit false"
        self.header = header
        self.palette = palette or {"tactics": {}, "theorems": {}}
        self.verifier = verifier or verify_lean_proof
        self.max_steps = max_steps
        self.lean_timeout = lean_timeout
        # strict_steps rejects semicolon-chained mega-tactics so an episode
        # reflects genuine step-level play (`<;>` combinators stay legal).
        self.strict_steps = strict_steps
        self.steps: List[str] = []
        self._goal_history: List[List[str]] = []
        self.transcript: List[Dict[str, Any]] = []
        self.done = False
        self.success = False
        #: Set by `reset()` when it refuses to start: "statement" (Lean read the
        #: statement and rejected it) or "verifier" (Lean never got to judge).
        self.reset_error_kind: Optional[str] = None

    # -- assembly -----------------------------------------------------------

    def assembled_code(self, steps: Optional[List[str]] = None) -> str:
        tactics = list(self.steps if steps is None else steps)
        body_lines = [f"  {line}" for tactic in tactics for line in tactic.splitlines()]
        if not body_lines:
            body_lines = ["  skip"]
        return f"{self.header}\n\n{self.statement} := by\n" + "\n".join(body_lines)

    async def _verify(self, steps: List[str]) -> LeanVerifyResult:
        code = self.assembled_code(steps)
        try:
            verdict = await self.verifier(code, timeout=self.lean_timeout)
        except TypeError:
            verdict = await self.verifier(code)
        if not isinstance(verdict, LeanVerifyResult):
            verdict = LeanVerifyResult(**dict(verdict))
        return verdict

    @staticmethod
    def _classify(verdict: LeanVerifyResult) -> tuple[str, List[str], str]:
        """→ (kind, goals, message); kind ∈ solved | active | rejected | error."""
        if verdict.system_error:
            return "error", [], verdict.system_error
        if verdict.complete:
            return "solved", [], "All goals closed."
        unsolved = [e for e in verdict.errors if _UNSOLVED_RE.search(e.body)]
        hard = [e for e in verdict.errors if not _UNSOLVED_RE.search(e.body)]
        if hard:
            summary = "; ".join(e.body.splitlines()[0][:160] for e in hard[:2])
            return "rejected", [], summary
        if unsolved:
            goals: List[str] = []
            for message in unsolved:
                goals.extend(_split_goal_blocks(message.body))
            return "active", goals, f"{len(goals)} open goal(s)."
        # ok with warnings only and not complete (e.g. sorry) — treat active.
        return "active", [], verdict.summary()[:200]

    # -- lifecycle ----------------------------------------------------------

    async def reset(self) -> ExamObservation:
        self.steps = []
        self._goal_history = []
        self.transcript = []
        self.done = False
        self.success = False
        self.reset_error_kind = None
        verdict = await self._verify([])
        kind, goals, message = self._classify(verdict)
        if kind == "solved":  # `skip` alone cannot solve; defensive.
            observation = self._observe("solved", [], message)
        elif kind in {"rejected", "error"}:
            # `rejected` is the statement: Lean read it and would not accept it.
            # `error` is the verifier: a REPL timeout, a decode failure, a dead
            # child. They end the episode the same way and would read the same
            # way — "exam statement invalid" — which turns a transport glitch
            # into a permanent verdict on a row that is fine. One REPL JSON
            # decode error was recorded exactly that way before this split.
            self.reset_error_kind = "statement" if kind == "rejected" else "verifier"
            label = ("exam statement invalid" if kind == "rejected"
                     else "verifier failed before the statement could be judged")
            observation = self._observe("error", [], f"{label}: {message}")
            self.done = True
        else:
            self._goal_history = [goals]
            observation = self._observe("active", goals, message)
        self.transcript.append({"action": {"type": "reset"}, "observation": observation.to_dict()})
        return observation

    def _observe(
        self,
        status: str,
        goals: List[str],
        message: str,
        card: Optional[Dict[str, str]] = None,
    ) -> ExamObservation:
        return ExamObservation(
            goals=goals,
            status=status,
            message=message,
            card=card,
            steps=list(self.steps),
            step_count=len(self.steps),
            done=self.done,
            success=self.success,
        )

    def _current_goals(self) -> List[str]:
        return list(self._goal_history[-1]) if self._goal_history else []

    async def step(self, action: Dict[str, Any]) -> ExamObservation:
        kind = str(action.get("type") or "").strip()
        if self.done:
            observation = self._observe(
                "error", self._current_goals(), "exam already finished"
            )
        elif kind == "inspect":
            observation = self._inspect(str(action.get("name") or ""))
        elif kind == "rollback":
            observation = self._rollback(int(action.get("to_step") or 0))
        elif kind == "tactic":
            observation = await self._play(str(action.get("tactic") or "").strip())
        else:
            observation = self._observe(
                "error", self._current_goals(), f"unknown action type: {kind!r}"
            )
        self.transcript.append(
            {"action": dict(action), "observation": observation.to_dict()}
        )
        return observation

    def _inspect(self, name: str) -> ExamObservation:
        for section in ("tactics", "theorems"):
            entry = (self.palette.get(section) or {}).get(name)
            if entry:
                card = {"name": name, "kind": section[:-1], "doc": entry}
                return self._observe(
                    "active", self._current_goals(), f"card: {name}", card
                )
        return self._observe(
            "active",
            self._current_goals(),
            f"no palette card named {name!r}",
        )

    def _rollback(self, to_step: int) -> ExamObservation:
        if not 0 <= to_step <= len(self.steps):
            return self._observe(
                "rejected",
                self._current_goals(),
                f"rollback target {to_step} out of range 0..{len(self.steps)}",
            )
        self.steps = self.steps[:to_step]
        self._goal_history = self._goal_history[: to_step + 1]
        return self._observe(
            "active",
            self._current_goals(),
            f"rolled back to step {to_step}",
        )

    async def _play(self, tactic: str) -> ExamObservation:
        if not tactic:
            return self._observe("rejected", self._current_goals(), "empty tactic")
        if self.strict_steps and ";" in tactic.replace("<;>", ""):
            return self._observe(
                "rejected",
                self._current_goals(),
                "strict mode: play one tactic per action (no ';' chains; "
                "`<;>` is allowed)",
            )
        if len(self.steps) >= self.max_steps:
            self.done = True
            return self._observe(
                "error", self._current_goals(), "step budget exhausted"
            )
        candidate = [*self.steps, tactic]
        verdict = await self._verify(candidate)
        kind, goals, message = self._classify(verdict)
        if kind == "solved":
            self.steps = candidate
            self._goal_history.append([])
            self.done = True
            self.success = True
            return self._observe("solved", [], message)
        if kind == "active":
            self.steps = candidate
            self._goal_history.append(goals)
            return self._observe("accepted", goals, message)
        if kind == "error":
            return self._observe("error", self._current_goals(), message)
        return self._observe("rejected", self._current_goals(), message)

    def solved_code(self) -> Optional[str]:
        return self.assembled_code() if self.success else None
